toolbar:
  - formatselect bold italic bullist numlist blockqoute alignleft aligncenter alignright undo redo image link code
plugins:
  - image
  - link
  - wordcount
  - code
relative_urls: false
remove_script_host: false
